experiment:
    debug_mode: True
    device: 'cpu'
    seed: 0
    agent_name: 'rsmpc'
    n_epochs: 50
    n_cycles: 50
    n_rollouts: 2
    n_train_batches: 40
env:
    id: 'ShadowHandReach-v0'
    max_episode_steps: 50
agent:
    buffer_size: 1000000
    lr_dynamics: 0.001
    batch_size: 256
    horizon: 5
    n_samples: 100
test:
    visualize: True
    n_episodes: 10
    gif: True
