HalfCheetahBulletEnv-v0: &pybullet-defaults
  n_ensemble: 7
  n_elite: 5
  n_reward: 1
  n_hidden: 256
  lr: 0.001
  dr: 0.05
  loss_decay: False
  train_freq: 250
  rollout_batch_size: 100000
  rollout_length: 1
  batches: 10000
  batch_size: 256
  holdout_ratio: 0.2
  max_epochs_since_update: 5
  buffer_size: 1000000
  model_type: 'deterministic'
  train_freq_policy: 1
  gradient_steps_policy: 1
  batch_size_policy: 2048

AntBulletEnv-v0:
  <<: *pybullet-defaults

HopperBulletEnv-v0:
  <<: *pybullet-defaults

Walker2DBulletEnv-v0:
  <<: *pybullet-defaults

PandaReach-v1:
  <<: *pybullet-defaults

PandaPush-v1:
  <<: *pybullet-defaults
  n_reward: 0
  batch_size: 256
  gradient_steps_policy: 200

ShadowHandReach-v1:
  <<: *pybullet-defaults
  n_reward: 0