experiment:
    debug_mode: True
    device: 'cpu'
    seed: 0
    agent_name: 'rsmpc'
    n_epochs: 100
    n_cycles: 1
    n_rollouts: 1
    #n_train_batches: 200
env:
    id: 'Pendulum-v0'
    max_episode_steps: 200
agent:
    buffer_size: 1000000
    lr_dynamics: 0.001
    batch_size: 100
    horizon: 20
    n_samples: 100
test:
    visualize: True
    n_episodes: 10
    gif: True
