experiment:
    debug_mode: True
    device: 'cpu'
    seed: 0
    agent_name: 'cem'
    n_epochs: 100
    n_cycles: 1
    n_rollouts: 1
env:
    id: 'MountainCarContinuous-v0'
    max_episode_steps: 500
    end_on_done: True
agent:
    buffer_size: 1000000
    lr_dynamics: 0.001
    batch_size: 100
    horizon: 20
    max_iter: 3
    population_size: 100
    n_elite: 25
    alpha: 0.0
    init_mean: 0.0
    init_variance: 1.0
    epsilon: 0.01
    sampler: 'truncated_normal'
test:
    visualize: True
    n_episodes: 10
    gif: True
