experiment:
    debug_mode: True
    device: 'cpu'
    seed: 0
    agent_name: 'ddpg'
    n_epochs: 200
    n_cycles: 1
    n_rollouts: 1
    #n_train_batches: 40
env:
    id: 'PandaReach-v0'
    max_episode_steps: 50
agent:
    buffer_size: 1000000
    lr_actor: 0.001
    lr_critic: 0.001
    noise_eps: 0.2
    noise_eps_min: 0.0
    noise_eps_decay: 0.0
    batch_size: 256
    gamma: 0.98
    polyak: 0.001
    random_exploration: 0.3
test:
    visualize: True
    n_episodes: 10
    gif: True