PandaReach-v1:
    env_wrapper: sb3_contrib.common.wrappers.TimeFeatureWrapper
    n_timesteps: !!float 20000
    policy: 'MultiInputPolicy'
    buffer_size: 1000000
    ent_coef: 'auto'
    batch_size: 256
    gamma: 0.95
    learning_rate: 0.001
    learning_starts: 1000
    normalize: True
    replay_buffer_class: HerReplayBuffer
    replay_buffer_kwargs: "dict(
        online_sampling=True,
        goal_selection_strategy='future',
        n_sampled_goal=4
    )"
    policy_kwargs: "dict(net_arch=[64, 64], n_critics=1)"

PandaPush-v1: &her-defaults
    env_wrapper: sb3_contrib.common.wrappers.TimeFeatureWrapper
    n_timesteps: !!float 1e6
    policy: 'MultiInputPolicy'
    buffer_size: 1000000
    ent_coef: 'auto'
    batch_size: 2048
    gamma: 0.95
    learning_rate: !!float 1e-3
    tau: 0.05
    replay_buffer_class: HerReplayBuffer
    replay_buffer_kwargs: "dict(
        online_sampling=True,
        goal_selection_strategy='future',
        n_sampled_goal=4,
    )"
    policy_kwargs: "dict(net_arch=[400, 300], n_critics=1)"
    # learning_starts: 1000
    callback:
        - callbacks.hybrid_callback.HyBridCallback:
            log_path: 'logs'
            algo_prefix: 'hb-'
            test_confidence_every: 5000
            random_exploration: 0.0

PandaSlide-v1:
    <<: *her-defaults
    n_timesteps: !!float 3e6

PandaPickAndPlace-v1:
    <<: *her-defaults

PandaStack-v1:
    <<: *her-defaults

ShadowHandReach-v1:
    env_wrapper: sb3_contrib.common.wrappers.TimeFeatureWrapper
    n_timesteps: !!float 100000
    policy: 'MultiInputPolicy'
    buffer_size: 1000000
    ent_coef: 'auto'
    batch_size: 256
    gamma: 0.95
    tau: 0.001
    learning_rate: 0.001
    learning_starts: 500
    normalize: True
    replay_buffer_class: HerReplayBuffer
    replay_buffer_kwargs: "dict(
        online_sampling=True,
        goal_selection_strategy='future',
        n_sampled_goal=4
    )"
    policy_kwargs: "dict(net_arch=[256, 256, 256], n_critics=1)"
    callback:
        - callbacks.hybrid_callback_2.HyBridCallback:
            log_path: 'logs'
            algo_prefix: 'hb-'